### ISSUE TITLE
First Changes: Checklist

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#32]

**Comment by vhellstein** [comment]
- [ ] tiles more like [Perfectly Imperfect](https://buncheong.denartmus.org/checklist/): white background, each tile the same size BUT with images aligned at top and text aligned at bottom; tile has designer/artist, title only @1000camels 

- [ ] order: alphabetical by artist @1000camels 

- [ ] Remove EXRRs @vhellstein 

- [ ] for objects with multiples within it: 1 image on left, then list of objects in text on right—follow Kit’s Word Doc for checklist @vhellstein  

- [ ] include link back to full checklist in each tile @1000camels 

- [ ] only arrows (not text) at top on navigation bar. @1000camels is this possible? Not sure we can treat the Nav bar differently in this section

- [ ] Just in checklist: include image credit information in text block, and not as caption with image at all. @mpopke I probably should check with Renee about this. But if OK, I can handle this in yaml files.

**Comment by 1000camels** [comment]
Confirming you want artist title? These are the title value in the individual md files, but I have a script that can update them

**Comment by 1000camels** [comment]
I've made exceptions for some names when sorting, but there may be further corrections you need if some tiles are not in the order you expect

**Comment by vhellstein** [comment]
> Confirming you want artist - title, instead of title - artist? These are the title value in the individual md files, but I have a script that can update them.

Artist, _Title_ is preferred. I had started making these changes yesterday and was going to finish today. I'll keep going and hope what I do doesn't interfere!

**Comment by 1000camels** [comment]
both the title, short_title and order fields in the checklist/<object_id>.md files are all generated by my script. You can add anything else to those files and it will be preserved.
Of course, I not run my script, but if we have to adjust the order in any way, it would be easier to do with the script.

**Comment by 1000camels** [comment]
Here is the order I can apply:

401 Ronan Bouroullec and Erwan Bouroullec, *Algues*
402 Humberto Campana and Fernando Campana, *Bulbo*
403 Nacho Carbonell, *One-Seater Concrete Tree*
404 Sandra Davolio, *Coral Flower I*
405 Sandra Davolio, *Coral Flower IV*
406 Sandra Davolio, *Vessel with Blue Edges III*
407 Jason DeMarte, *Arcadia*
408 DRIFT, *Meadow*
409 Shylight - DRIFT
410 Marc Fish, *Ethereal Double Console*
411 Front Design, *Curve Floor Lamps*
412 Clay Houses (Boulder-Room-Holes) - Andy Goldsworthy
413 gt2P (great things to People), *Remolten N1: Revolution Stools* and *Aux Table*
414 J. MAYER H., Metropol Parasol, Seville, Spain
415 Metropol Parasol, Seville, Spain, 2004-11. Drawings, 2007. - J. Mayer H.
416 Zaha Hadid, *Tau Vases*
417 Tau Vase - Zaha Hadid
418 Tau Vase - Zaha Hadid
419 Simon Heijdens, *Lightweeds*
420 Iris van Herpen, *Diatom Gown*
421 Iris van Herpen, *Dress*
422 Aranda&#92;Lasch and Terrol Dew Johnson, *Desert Paper 02*
423 Aranda&#92;Lasch and Terrol Dew Johnson, *Desert Paper 05*
424 Aranda&#92;Lasch and Terrol Dew Johnson, *Desert Paper 09*
425 Alexandra Kehayoglou, *Bajío*
426 Bone Armchair (prototype) - Joris Laarman
427 drawings for Microstructures Adaptation Chair (Long Cell) Prototype - Joris Laarman
428 Joris Laarman, *Microstructures Adaptation Chair (Long Cell) Prototype*
429 Mathieu Lehanneur, *50 Seas*
430 Mathieu Lehanneur, *Tomorrow is Another Day* (*Demain est un Autre Jour*)
431 Mathieu Lehanneur, *Ocean Memories (Circular Low Table Black XL)*
432 Mathieu Lehanneur, *Permanent Flame*
433 Greg Lynn, *Flatware Prototype Sketch*
434 Greg Lynn, *Flatware Prototype Sketch*
435 Greg Lynn, *Flatware Set*
436 MAD Architects, Nanjing Zendai Himalayas Center, Nanjing, China
437 Elena Manferdini, *Wall Flowers (Clover)*
438 Brad Miller, *Plate*
439 Brad Miller, *Plate*
440 Brad Miller, *Vessel*
441 Brad Miller, *Vessel*
442 Nervous System, *Floraform Chandelier*
443 Álvaro Catalán de Ocón, *Plastic River No. 6: Ganges*
444 PELLE, *Nana Lure Chandelier*
445 Andrés Reisinger, *Hortensia Armchair*
446 Andreea Avram Rusu, *Botanica Chandelier*
447 Fredrikson Stallard, *Rock #22*
448 Fredrikson Stallard, *Species 1*
449 Studio Gang, Populus, Denver, Colorado
450 Nao Tamura, *Petals Plates*
451 Nao Tamura, *Seasons Plates*
452 Nao Tamura, *Seasons Plates*
453 Nao Tamura, *Seasons Serving Platter*
454 teamLab, *Flowers and People – A Whole Year per Hour*
455 threeASFOUR, *Autumn Leaf Suit*
456 threeASFOUR, *Eve Dress*
457 threeASFOUR, *Lily Dress*
458 David Valner, *Fungus Vases* and *Polypore Bowl*

The only one that I think you might want sorted differently is Aranda\Lasch and Terrol Dew Johnson. What should that be sorted under?

As you can see, a few need their title's fixed. I'll leave that to you @vhellstein as it appears you are shortening them in some cases.

Finally, I can also add back the short_title: " " which removes titles from the navigation, leaving only arrows

**Comment by 1000camels** [comment]
I can work with the ordering as long as it has a logic.
My understanding is that you want 'Aranda\Lasch and Terrol Dew Johnson' sorted on ARANDA
And 'Andreea Avram Rusu' sorted on AVRAM.

If those are the only exceptions, I can code those.

I will still leave the title corrections to you

**Comment by vhellstein** [comment]
There are other exceptions
Fredrikson Stallard sorted on Fredrikson
MAD Architects sorted on MAD
Iris van Herpen sorted on VAN
Nervous System sorted on NERVOUS
Front Design sorted on FRONT
J. Mayer H. sorted on J

**Comment by 1000camels** [comment]
Alright let me apply those exceptions and see if I can get it sorted correctly

**Comment by 1000camels** [comment]
How do you want the credit information in text block shown? It does appear in the lightbox. I worry it will cause issues to display it on the thumbnail.

**Comment by vhellstein** [comment]
@1000camels Darrin wanted the credit line text to be a bit smaller than the rest of the text in the text block. By thumbnail, do you mean the image on the tile? We don't want the credit line of the tile. But maybe I'm misunderstanding.
