### ISSUE TITLE
Second Changes: Checklist

### ISSUE THREAD

**Issue by vhellstein** [DenverArtMuseum/biophilia-pub#52]

**Comment by vhellstein** [comment]
- [ ] @1000camels We decided to keep background color the same as rest of catalog

- [ ] @1000camels Can we add a note under "Checklist" that says: Objects are listed alphabetically by designer.

- [ ] @vhellstein to check all images and content against image logs

- [ ] @1000camels Right now, the text on the tiles bottom aligned. Can we make that text space fixed at 3 lines high and align at the top of that? (see image)


![Image](https://github.com/DenverArtMuseum/biophilia-pub/assets/119438504/f24aa40b-f491-4dd6-a83d-de6dfb69a6ed)

- [ ] @vhellstein to create md file for Laarman chair studies

- [ ] @1000camels a couple of more changes to the order. But I am also going to discuss with Darrin about giving all the items on the checklist numbers, so that might ease the ordering process?:
        - [ ] Álvaro Catalán de Ocón should be under "C"

        - [ ] J. MAYER H. should be under “J” 

        - [ ] Put Greg Lynn flatware before Greg Lynn sketches

        - [ ] Laarman chair studies come after Microstructures chair

- [ ] @vhellstein will check that all reproductions include dims in object.yaml

**Comment by vhellstein** [comment]
@1000camels We've decided to number the checklist with "Cat. #s"--this will just be a line in the objects.yaml and will need appear below the credit line and at the same size font. It won't appear on the checklist tiles. **If I go ahead and add this in the objects.yaml, will that make the sort easier? I had to add a couple of new checklist objects, too.**

**Comment by vhellstein** [comment]
@1000camels , there are a few objects in the checklist that are part of the museum's collection, and Darrin wanted to link to the online collection pages. I added the links, and they currently look like this:

![Image](https://github.com/DenverArtMuseum/biophilia-pub/assets/119438504/0ba7c622-6e07-4ab6-a4af-9df3b7e9cb1a)

Can we hide the link below the credit line and only have the "View in Collection" button?

**Comment by vhellstein** [comment]
@1000camels Matt fixed the ordering of the checklist

**Comment by 1000camels** [comment]
@mpopke at some point, I should show you the node script I created (bin/reorder_checklist.js).
It could be useful for new projects or for fixing ordering issues.
